### ISSUE TITLE
React 19 library compat

### ISSUE THREAD

**Issue by eps1lon** [eps1lon/react#10]
## how to read this

Checked checkboxes means resolved. Unchecked means unresolved.

- [ ] (impact) `library-name` some explainer and a link to the tracking issue

## unknown impact

- [ ] `framer-motion`: https://github.com/framer/motion/pull/2667
- [ ] `@react-pdf/renderer`: https://github.com/diegomura/react-pdf/issues/2756
- [ ] `@tremor/react`: https://github.com/tremorlabs/tremor/issues/1054
- [ ] `react-draggable` uses `findDOMNode`: https://github.com/react-grid-layout/react-draggable/issues/749
- [x] `@uiw/react-codemirror` uses secret internals in a published file: https://github.com/uiwjs/react-codemirror/pull/655

## production

- [x] (crash) `@headlessui/react` https://github.com/tailwindlabs/headlessui/issues/3167
- [x] (not working ) `recharts` fixed `[2.13.0-alpha.4](https://www.npmjs.com/package/recharts/v/2.13.0-alpha.4)` (https://github.com/recharts/recharts/issues/3615)

## dev-only

- [x] (warning: element.ref) `@radix-ui/react*` https://github.com/radix-ui/primitives/issues/2769 being fixed in https://github.com/radix-ui/primitives/pull/2934
- [x] (warning: element.ref) `react-email` fixed in https://github.com/resend/react-email/pull/1514
- [x] (warning: element.ref) `cmdk` fixed in https://github.com/pacocoursey/cmdk/pull/278
- [ ] (warning: element.ref) `basehub` tracking in https://github.com/basehub-ai/basehub/pull/111

## Types

- [ ] `@react-spring/web` ships global JSX namespace
- [x] Emotion: andarist is informed. Will be fixed in next major that uses new React 19 APIs.
- [ ] `@headlessui/react` declares components as forwardref render functions (see https://github.com/eps1lon/reactjs.org/pull/1)
- [ ] `styled-jsx` ships global JSX namespace: https://github.com/eps1lon/next.js/pull/1
- [ ] `framer-motion` ships global JSX namespace, `ReactHTML`, and `DetailedHTMLFactory`: https://github.com/eps1lon/react-spectrum/pull/1
- [ ] `lucide-react` uses `ReactSVG`
- [ ] React aria: https://github.com/adobe/react-spectrum/issues/6276
- [ ] react-redux: https://github.com/reduxjs/react-redux/issues/2162
- [ ] react-router: https://github.com/remix-run/react-router/discussions/11506
- [ ] MUI: https://github.com/mui/material-ui/issues/42032
